### ISSUE TITLE
Calls to IntrinioDataPoint("APLE", "last_price") always hit in cache

### ISSUE THREAD

**Issue by GernB4** [qalydon/intrinio-localc#2]
It seems as if most Intrinio-localc calls will hit in the cache rather than return the most recent data, and I can find no way to manually clear the cache.

**Comment by qalydon** [comment]
Unfortunately, you are correct. There is no easy way to clear the cache used by the IntrinioDataPoint function. The only way to clear the cache is to close LibreOffice. Closing the sheet will not clear the cache as it is maintained during the life of LibreOffice.

This design occurred for two reasons. First, the Intrinio Excel add-in works that way. That's not the greatest reason, but I'm guessing they did it for a reason, so I did it that way, too. Second, it prevents out-of-control Intrinio calls that use up your API credits. I use a free account which has a 500 call daily limit. Finally, this design was not aimed at a real-time application, rather it was aimed at non-real-time uses.

However, I would like to come with some sort of viable solution that accommodates your needs. I've come up with at least three candidate solutions.
1. Use a configuration setting to turn caching on/off. This could be for the entire plug-in or it could be on a function basis. For example, you could turn off caching for all IntrinioDataPoint calls.
2. Create a new function (or functions if so needed) that did not use caching. For example, IntrinioDataPointNC. Since most of the Intrinio functions are historical in nature (static results data), I would start with IntrinioDataPoint.
3. Add a cache control option to certain functions. For example, IntrinioDataPoint("APPL", "last_price", 0). Here, the last parameter is the cache control. 0 is false and means skip caching. 1 is true meaning use caching.

I have a slight preference for solution #2. Let me know if you have a preference for one of these or if you have another alternative.

**Comment by GernB4** [comment]
I think either solution 2 or 3 sounds fine. Solution 3 is a little more flexible since it allows dynamic alteration of the caching, however it does create an inconsistency with the Excel version. There is a fourth option, and that is to add an extension call to specifically clear the cache. That would be a viable solution as well, since it could be tied to some kind of update button. In the end any of the methods you propose would work.

**Comment by GernB4** [comment]
BTW. I think the problem in my use case is that I develop story plots using spreadsheets and use Writer to work on chapters. So both are open almost all the time. Meaning I rarely close LibreOffice. So it is common to come back the next day to look at a financial spreadsheet and have the exact same stock market prices as the day before..

**Comment by qalydon** [comment]
I've posted a new version of Intrinio LoCalc - 0.2.22. In this version I've implemented a cache life control for IntrinioDataPoint. It is sort of a combination of solutions #1 and #3 from above. I've updated the README.md file appropriately.

Data cached by IntrinioDataPoint is now subject to a cache life. When the cache life expires the data is considered stale and will be re-retrieved. The cache life defaults to 180 seconds or 3 minutes. You can change the cache life value through the intrinio.conf file (see README.md). If you want no caching for IntrinioDataPoint, set the cache life to 0. If you want "forever" caching, set cache life to an extremely large value. For example, 604800 is one week and 31449600 is one year.

Please let me know how this works for you. If it is adequate I will close this issue.

**Comment by GernB4** [comment]
It seems to work great. Thanks.

I personally like the fact that by default it times out after 180 seconds. However, I feel obligated to point out that it does alter the default behavior, thus creating a minor inconsistency with older versions.

I might also suggest that the comment you put in this thread might also be appropriate for the documentation: " If you want no caching for IntrinioDataPoint, set the cache life to 0. If you want "forever" caching, set cache life to an extremely large value. For example, 604800 is one week and 31449600 is one year."
